name: Continuous Delivery

on:
  push:
    branches:
      - master
      - release/*

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out source code
        uses: actions/checkout@v1

      - name: Setting up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies as CI
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on packages
        run: npm test

      - name: Bump package versions
        run: npm run version

      - name: Build packages
        run: npm run build

      - name: Publish public packages
        run: lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy documentation package to GitHub Pages
        run: npm run docs:deploy
