name: Continuous Delivery

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, test, version, build, publish packages and docs
      run: |
        npm ci
        npm test
        npm run version
        npm run build
        lerna publish from-git --yes
        npm run docs:deploy
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        CI: true
