name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - name: Checking out source code
        uses: actions/checkout@v1

      - name: Setting up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          scope: trutoo

      - name: Install dependencies as CI
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests on packages
        run: npm test

      - name: Bump package versions
        run: npm run version

      - name: Build packages
        run: npm run build
